server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://115.159.114.72:3306/food-mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: admin123456
  redis:
    database: 1
    host: 115.159.114.72
    port: 6379
    password: 123456

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl