server:
  port: 8080

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/food-mall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: admin123456